import { pgTable, uuid, varchar, text, jsonb, boolean, timestamp, integer, index, uniqueIndex } from 'drizzle-orm/pg-core'

export const tenants = pgTable(
  'tenants',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    name: varchar('name', { length: 255 }).notNull(),
    slug: varchar('slug', { length: 100 }).notNull().unique(),
    type: varchar('type', { length: 50 }).default('company'),
    status: varchar('status', { length: 50 }).default('active'),
    domain: varchar('domain', { length: 255 }),
    logo: varchar('logo', { length: 500 }),
    favicon: varchar('favicon', { length: 500 }),
    config: jsonb('config').default({}),
    metadata: jsonb('metadata').default({}),
    plan: varchar('plan', { length: 50 }).default('free'),
    planExpiresAt: timestamp('plan_expires_at', { withTimezone: true }),
    settings: jsonb('settings').default({}),
    sortOrder: integer('sort_order').default(0),
    isActive: boolean('is_active').default(true),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('idx_tenant_slug').on(table.slug),
    uniqueIndex('idx_tenant_domain').on(table.domain),
    index('idx_tenant_type').on(table.type),
    index('idx_tenant_status').on(table.status),
    index('idx_tenant_plan').on(table.plan),
    index('idx_tenant_sort_order').on(table.sortOrder),
  ],
)

export const countries = pgTable(
  'countries',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    code: varchar('code', { length: 2 }).notNull().unique(),
    name: varchar('name', { length: 255 }).notNull(),
    nativeName: varchar('native_name', { length: 255 }),
    flagEmoji: varchar('flag_emoji', { length: 10 }),
    flagSvg: varchar('flag_svg', { length: 500 }),
    currency: varchar('currency', { length: 3 }),
    currencySymbol: varchar('currency_symbol', { length: 10 }),
    phoneCode: varchar('phone_code', { length: 10 }),
    timezone: varchar('timezone', { length: 100 }),
    locale: varchar('locale', { length: 10 }),
    dateFormat: varchar('date_format', { length: 50 }),
    timeFormat: varchar('time_format', { length: 20 }),
    metadata: jsonb('metadata').default({}),
    isActive: boolean('is_active').default(true),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('idx_country_code').on(table.code),
    index('idx_country_currency').on(table.currency),
    index('idx_country_timezone').on(table.timezone),
    index('idx_country_locale').on(table.locale),
  ],
)

export const regions = pgTable(
  'regions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    countryId: uuid('country_id').notNull().references(() => countries.id, { onDelete: 'restrict' }),
    code: varchar('code', { length: 20 }).notNull(),
    name: varchar('name', { length: 255 }).notNull(),
    nativeName: varchar('native_name', { length: 255 }),
    type: varchar('type', { length: 50 }).default('state'),
    coordinates: jsonb('coordinates').default({ lat: 0, lng: 0 }),
    boundingBox: jsonb('bounding_box').default({}),
    metadata: jsonb('metadata').default({}),
    sortOrder: integer('sort_order').default(0),
    isActive: boolean('is_active').default(true),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index('idx_region_country_id').on(table.countryId),
    uniqueIndex('idx_region_country_code').on(table.countryId, table.code),
    index('idx_region_sort_order').on(table.sortOrder),
  ],
)

export const destinations = pgTable(
  'destinations',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    regionId: uuid('region_id').notNull().references(() => regions.id, { onDelete: 'restrict' }),
    code: varchar('code', { length: 50 }).notNull(),
    name: varchar('name', { length: 255 }).notNull(),
    slug: varchar('slug', { length: 100 }).notNull().unique(),
    type: varchar('type', { length: 50 }).default('tourism'),
    description: text('description'),
    coordinates: jsonb('coordinates').default({ lat: 0, lng: 0 }),
    branding: jsonb('branding').default({}),
    seo: jsonb('seo').default({}),
    maps: jsonb('maps').default({}),
    analytics: jsonb('analytics').default({}),
    settings: jsonb('settings').default({}),
    enabledCategories: jsonb('enabled_categories').default([]),
    enabledModules: jsonb('enabled_modules').default([]),
    sortOrder: integer('sort_order').default(0),
    status: varchar('status', { length: 50 }).default('active'),
    isActive: boolean('is_active').default(true),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index('idx_destination_region_id').on(table.regionId),
    uniqueIndex('idx_destination_slug').on(table.slug),
    index('idx_destination_code').on(table.code),
    index('idx_destination_type').on(table.type),
    index('idx_destination_status').on(table.status),
    index('idx_destination_sort_order').on(table.sortOrder),
  ],
)

export const domains = pgTable(
  'domains',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    destinationId: uuid('destination_id').references(() => destinations.id, { onDelete: 'cascade' }),
    tenantId: uuid('tenant_id').references(() => tenants.id, { onDelete: 'cascade' }),
    name: varchar('name', { length: 255 }).notNull(),
    type: varchar('type', { length: 50 }).default('website'),
    subdomain: varchar('subdomain', { length: 100 }),
    isPrimary: boolean('is_primary').default(false),
    isVerified: boolean('is_verified').default(false),
    verifiedAt: timestamp('verified_at', { withTimezone: true }),
    sslEnabled: boolean('ssl_enabled').default(true),
    sslCertificate: jsonb('ssl_certificate').default({}),
    settings: jsonb('settings').default({}),
    metadata: jsonb('metadata').default({}),
    sortOrder: integer('sort_order').default(0),
    isActive: boolean('is_active').default(true),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('idx_domain_name').on(table.name),
    index('idx_domain_destination_id').on(table.destinationId),
    index('idx_domain_tenant_id').on(table.tenantId),
    index('idx_domain_subdomain').on(table.subdomain),
    index('idx_domain_type').on(table.type),
    index('idx_domain_is_primary').on(table.isPrimary),
  ],
)

export const themes = pgTable(
  'themes',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    destinationId: uuid('destination_id').references(() => destinations.id, { onDelete: 'cascade' }),
    tenantId: uuid('tenant_id').references(() => tenants.id, { onDelete: 'cascade' }),
    name: varchar('name', { length: 100 }).notNull(),
    slug: varchar('slug', { length: 100 }).notNull().unique(),
    type: varchar('type', { length: 50 }).default('light'),
    colors: jsonb('colors').default({
      primary: '#1976D2',
      secondary: '#424242',
      accent: '#FF5722',
      background: '#FFFFFF',
      surface: '#F5F5F5',
      error: '#D32F2F',
      success: '#388E3C',
      warning: '#FFA000',
      info: '#1976D2',
    }),
    typography: jsonb('typography').default({
      fontFamily: 'system-ui, sans-serif',
      headingFont: 'system-ui, sans-serif',
      bodyFont: 'system-ui, sans-serif',
      sizes: {},
    }),
    spacing: jsonb('spacing').default({}),
    borderRadius: jsonb('border_radius').default({}),
    shadows: jsonb('shadows').default({}),
    customCss: varchar('custom_css', { length: 10000 }),
    isDefault: boolean('is_default').default(false),
    isActive: boolean('is_active').default(true),
    sortOrder: integer('sort_order').default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('idx_theme_slug').on(table.slug),
    index('idx_theme_destination_id').on(table.destinationId),
    index('idx_theme_tenant_id').on(table.tenantId),
    index('idx_theme_is_default').on(table.isDefault),
    index('idx_theme_sort_order').on(table.sortOrder),
  ],
)

export const languages = pgTable(
  'languages',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    code: varchar('code', { length: 10 }).notNull().unique(),
    name: varchar('name', { length: 100 }).notNull(),
    nativeName: varchar('native_name', { length: 100 }),
    rtl: boolean('rtl').default(false),
    isDefault: boolean('is_default').default(false),
    isActive: boolean('is_active').default(true),
    sortOrder: integer('sort_order').default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('idx_language_code').on(table.code),
    index('idx_language_is_default').on(table.isDefault),
    index('idx_language_sort_order').on(table.sortOrder),
  ],
)

export const platformSchemas = {
  tenants,
  countries,
  regions,
  destinations,
  domains,
  themes,
  languages,
}

export default platformSchemas
