import { pgTable, uuid, varchar, text, jsonb, boolean, timestamp, integer, index, uniqueIndex } from 'drizzle-orm/pg-core'
import { destinations } from '../platform/index.js'

export const ecosystems = pgTable(
  'ecosystems',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    destinationId: uuid('destination_id').notNull().references(() => destinations.id, { onDelete: 'cascade' }),
    name: varchar('name', { length: 255 }).notNull(),
    slug: varchar('slug', { length: 100 }).notNull().unique(),
    type: varchar('type', { length: 50 }).default('tourism'),
    description: text('description'),
    logo: varchar('logo', { length: 500 }),
    coverImage: varchar('cover_image', { length: 500 }),
    branding: jsonb('branding').default({}),
    configuration: jsonb('configuration').default({}),
    features: jsonb('features').default([]),
    settings: jsonb('settings').default({}),
    metadata: jsonb('metadata').default({}),
    sortOrder: integer('sort_order').default(0),
    status: varchar('status', { length: 50 }).default('active'),
    isActive: boolean('is_active').default(true),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('idx_ecosystem_slug').on(table.slug),
    index('idx_ecosystem_destination_id').on(table.destinationId),
    index('idx_ecosystem_type').on(table.type),
    index('idx_ecosystem_status').on(table.status),
    index('idx_ecosystem_sort_order').on(table.sortOrder),
  ],
)

export const categories = pgTable(
  'categories',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    ecosystemId: uuid('ecosystem_id').notNull().references(() => ecosystems.id, { onDelete: 'cascade' }),
    parentId: uuid('parent_id'),
    name: varchar('name', { length: 255 }).notNull(),
    slug: varchar('slug', { length: 100 }).notNull().unique(),
    type: varchar('type', { length: 50 }).default('general'),
    icon: varchar('icon', { length: 100 }),
    description: text('description'),
    image: varchar('image', { length: 500 }),
    metadata: jsonb('metadata').default({}),
    settings: jsonb('settings').default({}),
    sortOrder: integer('sort_order').default(0),
    status: varchar('status', { length: 50 }).default('active'),
    isActive: boolean('is_active').default(true),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('idx_category_slug').on(table.slug),
    index('idx_category_ecosystem_id').on(table.ecosystemId),
    index('idx_category_parent_id').on(table.parentId),
    index('idx_category_type').on(table.type),
    index('idx_category_status').on(table.status),
    index('idx_category_sort_order').on(table.sortOrder),
  ],
)

export const modules = pgTable(
  'modules',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    ecosystemId: uuid('ecosystem_id').notNull().references(() => ecosystems.id, { onDelete: 'cascade' }),
    code: varchar('code', { length: 100 }).notNull(),
    name: varchar('name', { length: 255 }).notNull(),
    slug: varchar('slug', { length: 100 }).notNull().unique(),
    type: varchar('type', { length: 50 }).default('feature'),
    description: text('description'),
    version: varchar('version', { length: 20 }).default('1.0.0'),
    icon: varchar('icon', { length: 100 }),
    configuration: jsonb('configuration').default({}),
    capabilities: jsonb('capabilities').default([]),
    permissions: jsonb('permissions').default([]),
    dependencies: jsonb('dependencies').default([]),
    metadata: jsonb('metadata').default({}),
    settings: jsonb('settings').default({}),
    sortOrder: integer('sort_order').default(0),
    status: varchar('status', { length: 50 }).default('active'),
    isEnabled: boolean('is_enabled').default(false),
    isBuiltIn: boolean('is_built_in').default(false),
    isActive: boolean('is_active').default(true),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('idx_module_slug').on(table.slug),
    uniqueIndex('idx_module_code').on(table.ecosystemId, table.code),
    index('idx_module_ecosystem_id').on(table.ecosystemId),
    index('idx_module_type').on(table.type),
    index('idx_module_status').on(table.status),
    index('idx_module_is_enabled').on(table.isEnabled),
    index('idx_module_sort_order').on(table.sortOrder),
  ],
)

export const experiences = pgTable(
  'experiences',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    ecosystemId: uuid('ecosystem_id').notNull().references(() => ecosystems.id, { onDelete: 'cascade' }),
    categoryId: uuid('category_id').references(() => categories.id, { onDelete: 'set null' }),
    name: varchar('name', { length: 255 }).notNull(),
    slug: varchar('slug', { length: 100 }).notNull().unique(),
    type: varchar('type', { length: 50 }).default('tourism'),
    description: text('description'),
    shortDescription: varchar('short_description', { length: 500 }),
    image: varchar('image', { length: 500 }),
    gallery: jsonb('gallery').default([]),
    location: jsonb('location').default({}),
    navigation: jsonb('navigation').default({}),
    layouts: jsonb('layouts').default({}),
    workflows: jsonb('workflows').default({}),
    permissions: jsonb('permissions').default({}),
    i18n: jsonb('i18n').default({}),
    seo: jsonb('seo').default({}),
    metadata: jsonb('metadata').default({}),
    settings: jsonb('settings').default({}),
    sortOrder: integer('sort_order').default(0),
    status: varchar('status', { length: 50 }).default('draft'),
    isActive: boolean('is_active').default(true),
    publishedAt: timestamp('published_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('idx_experience_slug').on(table.slug),
    index('idx_experience_ecosystem_id').on(table.ecosystemId),
    index('idx_experience_category_id').on(table.categoryId),
    index('idx_experience_type').on(table.type),
    index('idx_experience_status').on(table.status),
    index('idx_experience_sort_order').on(table.sortOrder),
  ],
)

export const ecosystemSchemas = {
  ecosystems,
  categories,
  modules,
  experiences,
}

export default ecosystemSchemas
