/**
 * Booking Capability — Events
 *
 * Standard events for booking lifecycle
 */
import { CAPABILITY_EVENTS } from '../core/events.js'

export const BOOKING_EVENTS = {
  CREATED: CAPABILITY_EVENTS.BOOKING_CREATED,
  UPDATED: CAPABILITY_EVENTS.BOOKING_UPDATED,
  CANCELLED: CAPABILITY_EVENTS.BOOKING_CANCELLED,
  CONFIRMED: CAPABILITY_EVENTS.BOOKING_CONFIRMED,
  COMPLETED: CAPABILITY_EVENTS.BOOKING_COMPLETED,
}
