import { pgTable, uuid, varchar, text, jsonb, boolean, timestamp, integer, decimal, index, uniqueIndex } from 'drizzle-orm/pg-core'
import { tenants } from '../platform/index.js'
import { companies } from '../company/index.js'
import { categories } from '../ecosystem/index.js'
import { users } from '../identity/index.js'

export const accommodations = pgTable(
  'accommodations',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'restrict' }),
    companyId: uuid('company_id').notNull().references(() => companies.id, { onDelete: 'cascade' }),
    categoryId: uuid('category_id').references(() => categories.id, { onDelete: 'set null' }),
    ownerId: uuid('owner_id'),
    name: varchar('name', { length: 255 }).notNull(),
    slug: varchar('slug', { length: 100 }).notNull().unique(),
    type: varchar('type', { length: 50 }).default('hotel'),
    status: varchar('status', { length: 50 }).default('draft'),
    description: text('description'),
    shortDescription: varchar('short_description', { length: 500 }),
    images: jsonb('images').default([]),
    gallery: jsonb('gallery').default([]),
    location: jsonb('location').default({}),
    contact: jsonb('contact').default({}),
    amenities: jsonb('amenities').default([]),
    policies: jsonb('policies').default({}),
    rooms: jsonb('rooms').default([]),
    pricing: jsonb('pricing').default({}),
    inventory: jsonb('inventory').default({}),
    seo: jsonb('seo').default({}),
    branding: jsonb('branding').default({}),
    rating: decimal('rating', { precision: 3, scale: 2 }),
    reviewCount: integer('review_count').default(0),
    metadata: jsonb('metadata').default({}),
    settings: jsonb('settings').default({}),
    publishedAt: timestamp('published_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
    createdBy: uuid('created_by'),
    updatedBy: uuid('updated_by'),
  },
  (table) => [
    uniqueIndex('idx_accommodation_slug').on(table.slug),
    index('idx_accommodation_tenant_id').on(table.tenantId),
    index('idx_accommodation_company_id').on(table.companyId),
    index('idx_accommodation_category_id').on(table.categoryId),
    index('idx_accommodation_owner_id').on(table.ownerId),
    index('idx_accommodation_type').on(table.type),
    index('idx_accommodation_status').on(table.status),
    index('idx_accommodation_deleted_at').on(table.deletedAt),
  ],
)

export const accommodationUnits = pgTable(
  'accommodation_units',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    accommodationId: uuid('accommodation_id').notNull().references(() => accommodations.id, { onDelete: 'cascade' }),
    name: varchar('name', { length: 255 }).notNull(),
    slug: varchar('slug', { length: 100 }).notNull().unique(),
    type: varchar('type', { length: 50 }).default('room'),
    description: text('description'),
    images: jsonb('images').default([]),
    maxGuests: integer('max_guests').default(2),
    bedrooms: integer('bedrooms').default(1),
    bathrooms: integer('bathrooms').default(1),
    beds: jsonb('beds').default([]),
    amenities: jsonb('amenities').default([]),
    pricing: jsonb('pricing').default({}),
    inventory: jsonb('inventory').default({}),
    status: varchar('status', { length: 50 }).default('active'),
    sortOrder: integer('sort_order').default(0),
    isActive: boolean('is_active').default(true),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('idx_accommodation_unit_slug').on(table.slug),
    index('idx_accommodation_unit_accommodation_id').on(table.accommodationId),
    index('idx_accommodation_unit_type').on(table.type),
    index('idx_accommodation_unit_status').on(table.status),
  ],
)

export const availability = pgTable(
  'availability',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'restrict' }),
    accommodationId: uuid('accommodation_id').notNull().references(() => accommodations.id, { onDelete: 'cascade' }),
    date: varchar('date', { length: 20 }).notNull(),
    status: varchar('status', { length: 50 }).default('available'),
    isBlocked: boolean('is_blocked').default(false),
    isReserved: boolean('is_reserved').default(false),
    minStay: integer('min_stay'),
    maxStay: integer('max_stay'),
    arrivalDays: jsonb('arrival_days').default([]),
    departureDays: jsonb('departure_days').default([]),
    price: jsonb('price').default({}),
    inventory: integer('inventory').default(1),
    reservedCount: integer('reserved_count').default(0),
    metadata: jsonb('metadata').default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('idx_availability_accommodation_date').on(table.accommodationId, table.date),
    index('idx_availability_tenant_id').on(table.tenantId),
    index('idx_availability_status').on(table.status),
    index('idx_availability_is_blocked').on(table.isBlocked),
  ],
)

export const availabilityRules = pgTable(
  'availability_rules',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'restrict' }),
    accommodationId: uuid('accommodation_id').references(() => accommodations.id, { onDelete: 'cascade' }),
    name: varchar('name', { length: 255 }).notNull(),
    type: varchar('type', { length: 50 }).notNull(),
    config: jsonb('config').default({}),
    priority: integer('priority').default(0),
    startDate: varchar('start_date', { length: 20 }),
    endDate: varchar('end_date', { length: 20 }),
    daysOfWeek: jsonb('days_of_week').default([]),
    isActive: boolean('is_active').default(true),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index('idx_availability_rule_tenant_id').on(table.tenantId),
    index('idx_availability_rule_accommodation_id').on(table.accommodationId),
    index('idx_availability_rule_type').on(table.type),
    index('idx_availability_rule_is_active').on(table.isActive),
  ],
)

export const reservations = pgTable(
  'reservations',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'restrict' }),
    accommodationId: uuid('accommodation_id').notNull().references(() => accommodations.id, { onDelete: 'restrict' }),
    userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
    visitorId: uuid('visitor_id'),
    status: varchar('status', { length: 50 }).notNull().default('pending'),
    confirmationCode: varchar('confirmation_code', { length: 50 }).notNull().unique(),
    checkInDate: varchar('check_in_date', { length: 20 }).notNull(),
    checkOutDate: varchar('check_out_date', { length: 20 }).notNull(),
    checkInTime: varchar('check_in_time', { length: 20 }),
    checkOutTime: varchar('check_out_time', { length: 20 }),
    guestCount: integer('guest_count').default(1),
    adults: integer('adults').default(1),
    children: integer('children').default(0),
    infants: integer('infants').default(0),
    pets: integer('pets').default(0),
    subtotal: decimal('subtotal', { precision: 12, scale: 2 }),
    taxes: decimal('taxes', { precision: 12, scale: 2 }),
    fees: decimal('fees', { precision: 12, scale: 2 }),
    discount: decimal('discount', { precision: 12, scale: 2 }),
    totalPrice: decimal('total_price', { precision: 12, scale: 2 }),
    currency: varchar('currency', { length: 3 }).default('USD'),
    channel: varchar('channel', { length: 50 }),
    customer: jsonb('customer').default({}),
    guestDetails: jsonb('guest_details').default({}),
    specialRequests: text('special_requests'),
    internalNotes: text('internal_notes'),
    metadata: jsonb('metadata').default({}),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    confirmedAt: timestamp('confirmed_at', { withTimezone: true }),
    cancelledAt: timestamp('cancelled_at', { withTimezone: true }),
    checkedInAt: timestamp('checked_in_at', { withTimezone: true }),
    checkedOutAt: timestamp('checked_out_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
  },
  (table) => [
    uniqueIndex('idx_reservation_confirmation_code').on(table.confirmationCode),
    index('idx_reservation_tenant_id').on(table.tenantId),
    index('idx_reservation_accommodation_id').on(table.accommodationId),
    index('idx_reservation_user_id').on(table.userId),
    index('idx_reservation_visitor_id').on(table.visitorId),
    index('idx_reservation_status').on(table.status),
    index('idx_reservation_check_in_date').on(table.checkInDate),
    index('idx_reservation_check_out_date').on(table.checkOutDate),
    index('idx_reservation_channel').on(table.channel),
  ],
)

export const reservationActivities = pgTable(
  'reservation_activities',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    reservationId: uuid('reservation_id').notNull().references(() => reservations.id, { onDelete: 'cascade' }),
    activityType: varchar('activity_type', { length: 50 }).notNull(),
    description: text('description'),
    actorId: uuid('actor_id'),
    actorType: varchar('actor_type', { length: 50 }),
    oldStatus: varchar('old_status', { length: 50 }),
    newStatus: varchar('new_status', { length: 50 }),
    metadata: jsonb('metadata').default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index('idx_reservation_activity_reservation_id').on(table.reservationId),
    index('idx_reservation_activity_type').on(table.activityType),
  ],
)

export const payments = pgTable(
  'payments',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'restrict' }),
    reservationId: uuid('reservation_id').references(() => reservations.id, { onDelete: 'set null' }),
    userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
    amount: decimal('amount', { precision: 12, scale: 2 }).notNull(),
    currency: varchar('currency', { length: 3 }).notNull().default('USD'),
    status: varchar('status', { length: 50 }).notNull().default('pending'),
    type: varchar('type', { length: 50 }).default('payment'),
    method: varchar('method', { length: 50 }),
    provider: varchar('provider', { length: 50 }),
    providerReference: varchar('provider_reference', { length: 255 }),
    providerTransactionId: varchar('provider_transaction_id', { length: 255 }),
    gatewayResponse: jsonb('gateway_response').default({}),
    customer: jsonb('customer').default({}),
    billingDetails: jsonb('billing_details').default({}),
    metadata: jsonb('metadata').default({}),
    refundedAmount: decimal('refunded_amount', { precision: 12, scale: 2 }).default('0'),
    refundReason: text('refund_reason'),
    refundedAt: timestamp('refunded_at', { withTimezone: true }),
    processedAt: timestamp('processed_at', { withTimezone: true }),
    failedAt: timestamp('failed_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
  },
  (table) => [
    uniqueIndex('idx_payment_provider_reference').on(table.providerReference),
    index('idx_payment_tenant_id').on(table.tenantId),
    index('idx_payment_reservation_id').on(table.reservationId),
    index('idx_payment_user_id').on(table.userId),
    index('idx_payment_status').on(table.status),
    index('idx_payment_type').on(table.type),
    index('idx_payment_method').on(table.method),
  ],
)

export const invoices = pgTable(
  'invoices',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'restrict' }),
    invoiceNumber: varchar('invoice_number', { length: 50 }).notNull().unique(),
    reservationId: uuid('reservation_id').references(() => reservations.id, { onDelete: 'set null' }),
    customerId: uuid('customer_id'),
    status: varchar('status', { length: 50 }).default('draft'),
    issueDate: timestamp('issue_date', { withTimezone: true }),
    dueDate: timestamp('due_date', { withTimezone: true }),
    subtotal: decimal('subtotal', { precision: 12, scale: 2 }),
    tax: decimal('tax', { precision: 12, scale: 2 }),
    total: decimal('total', { precision: 12, scale: 2 }),
    currency: varchar('currency', { length: 3 }).default('USD'),
    items: jsonb('items').default([]),
    customerDetails: jsonb('customer_details').default({}),
    metadata: jsonb('metadata').default({}),
    paidAt: timestamp('paid_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('idx_invoice_number').on(table.invoiceNumber),
    index('idx_invoice_tenant_id').on(table.tenantId),
    index('idx_invoice_reservation_id').on(table.reservationId),
    index('idx_invoice_status').on(table.status),
  ],
)

export const reviews = pgTable(
  'reviews',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'restrict' }),
    accommodationId: uuid('accommodation_id').notNull().references(() => accommodations.id, { onDelete: 'cascade' }),
    reservationId: uuid('reservation_id').references(() => reservations.id, { onDelete: 'set null' }),
    userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
    visitorId: uuid('visitor_id'),
    rating: decimal('rating', { precision: 3, scale: 2 }).notNull(),
    title: varchar('title', { length: 255 }),
    content: text('content'),
    categories: jsonb('categories').default({}),
    pros: jsonb('pros').default([]),
    cons: jsonb('cons').default([]),
    images: jsonb('images').default([]),
    status: varchar('status', { length: 50 }).default('pending'),
    isVerified: boolean('is_verified').default(false),
    isFeatured: boolean('is_featured').default(false),
    helpfulCount: integer('helpful_count').default(0),
    response: jsonb('response').default({}),
    metadata: jsonb('metadata').default({}),
    publishedAt: timestamp('published_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
  },
  (table) => [
    index('idx_review_tenant_id').on(table.tenantId),
    index('idx_review_accommodation_id').on(table.accommodationId),
    index('idx_review_reservation_id').on(table.reservationId),
    index('idx_review_user_id').on(table.userId),
    index('idx_review_visitor_id').on(table.visitorId),
    index('idx_review_status').on(table.status),
    index('idx_review_rating').on(table.rating),
    index('idx_review_is_verified').on(table.isVerified),
    index('idx_review_published_at').on(table.publishedAt),
  ],
)

export const reviewHelpfulness = pgTable(
  'review_helpfulness',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    reviewId: uuid('review_id').notNull().references(() => reviews.id, { onDelete: 'cascade' }),
    userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
    isHelpful: boolean('is_helpful').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('idx_review_helpfulness_review_user').on(table.reviewId, table.userId),
    index('idx_review_helpfulness_review_id').on(table.reviewId),
    index('idx_review_helpfulness_user_id').on(table.userId),
  ],
)

export const businessNotifications = pgTable(
  'business_notifications',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id').references(() => tenants.id, { onDelete: 'set null' }),
    userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
    reservationId: uuid('reservation_id').references(() => reservations.id, { onDelete: 'set null' }),
    recipientId: uuid('recipient_id'),
    recipientType: varchar('recipient_type', { length: 50 }),
    type: varchar('type', { length: 100 }).notNull(),
    channel: varchar('channel', { length: 50 }).default('in_app'),
    priority: varchar('priority', { length: 20 }).default('normal'),
    subject: varchar('subject', { length: 255 }),
    title: varchar('title', { length: 255 }),
    content: jsonb('content').default({}),
    body: text('body'),
    data: jsonb('data').default({}),
    status: varchar('status', { length: 50 }).notNull().default('pending'),
    scheduledAt: timestamp('scheduled_at', { withTimezone: true }),
    sentAt: timestamp('sent_at', { withTimezone: true }),
    deliveredAt: timestamp('delivered_at', { withTimezone: true }),
    readAt: timestamp('read_at', { withTimezone: true }),
    failedAt: timestamp('failed_at', { withTimezone: true }),
    failureReason: text('failure_reason'),
    retryCount: integer('retry_count').default(0),
    metadata: jsonb('metadata').default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
  },
  (table) => [
    index('idx_business_notification_tenant_id').on(table.tenantId),
    index('idx_business_notification_user_id').on(table.userId),
    index('idx_business_notification_recipient_id').on(table.recipientId),
    index('idx_business_notification_reservation_id').on(table.reservationId),
    index('idx_business_notification_type').on(table.type),
    index('idx_business_notification_channel').on(table.channel),
    index('idx_business_notification_status').on(table.status),
    index('idx_business_notification_priority').on(table.priority),
    index('idx_business_notification_scheduled_at').on(table.scheduledAt),
    index('idx_business_notification_sent_at').on(table.sentAt),
    index('idx_business_notification_read_at').on(table.readAt),
  ],
)

export const notificationPreferences = pgTable(
  'notification_preferences',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }).unique(),
    email: boolean('email').default(true),
    sms: boolean('sms').default(false),
    push: boolean('push').default(true),
    whatsapp: boolean('whatsapp').default(false),
    inApp: boolean('in_app').default(true),
    reservationConfirmations: boolean('reservation_confirmations').default(true),
    reservationReminders: boolean('reservation_reminders').default(true),
    reservationCancellations: boolean('reservation_cancellations').default(true),
    marketing: boolean('marketing').default(false),
    newsletter: boolean('newsletter').default(false),
    digest: boolean('digest').default(false),
    frequency: varchar('frequency', { length: 20 }).default('instant'),
    quietHoursStart: varchar('quiet_hours_start', { length: 10 }),
    quietHoursEnd: varchar('quiet_hours_end', { length: 10 }),
    metadata: jsonb('metadata').default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('idx_notification_preference_user_id').on(table.userId),
    index('idx_notification_preference_email').on(table.email),
    index('idx_notification_preference_frequency').on(table.frequency),
  ],
)

export const businessSchemas = {
  accommodations,
  accommodationUnits,
  availability,
  availabilityRules,
  reservations,
  reservationActivities,
  payments,
  invoices,
  reviews,
  reviewHelpfulness,
  notifications: businessNotifications,
  notificationPreferences,
}

export default businessSchemas
