export const LABELS = {
  id: 'ID', name: 'Nombre', title: 'Título', subtitle: 'Subtítulo',
  description: 'Descripción', status: 'Estado', type: 'Tipo',
  category: 'Categoría', model: 'Modelo', manufacturer: 'Fabricante',
  year: 'Año', battery: 'Batería', speed: 'Velocidad', altitude: 'Altitud',
  heading: 'Rumbo', signal: 'Señal', temperature: 'Temperatura',
  weight: 'Peso', maxSpeed: 'Vel. Máxima', maxFlightTime: 'Vuelo Máx.',
  totalHours: 'Horas Totales', totalMissions: 'Misiones Totales',
  price: 'Precio', currency: 'Moneda', duration: 'Duración',
  email: 'Correo', phone: 'Teléfono', address: 'Dirección',
  role: 'Rol', bio: 'Biografía', skills: 'Habilidades',
  languages: 'Idiomas', certifications: 'Certificaciones',
  quote: 'Cita', rating: 'Calificación', tags: 'Etiquetas',
  client: 'Cliente', director: 'Director', synopsis: 'Sinopsis',
  format: 'Formato', resolution: 'Resolución', fps: 'FPS',
  codec: 'Codec', bitDepth: 'Bit Depth', chroma: 'Croma',
  container: 'Contenedor', useCase: 'Uso',
  followers: 'Seguidores', engagement: 'Engagement',
  question: 'Pregunta', answer: 'Respuesta',
  founded: 'Fundación', teamSize: 'Equipo',
  missionsCompleted: 'Misiones Completadas',
  hoursFlown: 'Horas de Vuelo', countriesReached: 'Países',
  awards: 'Premios', slug: 'Slug',
}
