export const VISITOR_EVENTS = Object.freeze({
  CREATED: 'visitor:created',
  UPDATED: 'visitor:updated',
  DELETED: 'visitor:deleted',
  ARCHIVED: 'visitor:archived',
  RESTORED: 'visitor:restored',
  MERGED: 'visitor:merged',
  VERIFIED: 'visitor:verified',
  ACTIVATED: 'visitor:activated',
  DEACTIVATED: 'visitor:deactivated',
  VIP_GRANTED: 'visitor:vip_granted',
  VIP_REVOKED: 'visitor:vip_revoked',
  BLACKLISTED: 'visitor:blacklisted',
  REMOVED_FROM_BLACKLIST: 'visitor:removed_from_blacklist',
  PROFILE_UPDATED: 'visitor:profile_updated',
  PREFERENCES_UPDATED: 'visitor:preferences_updated',
  STATISTICS_UPDATED: 'visitor:statistics_updated',
  RESERVATION_LINKED: 'visitor:reservation_linked',
  RESERVATION_REMOVED: 'visitor:reservation_removed',
  TAG_ADDED: 'visitor:tag_added',
  TAG_REMOVED: 'visitor:tag_removed',
})
