export const PAYMENT_EVENTS = Object.freeze({
  CREATED: 'payment:created',
  UPDATED: 'payment:updated',
  AUTHORIZED: 'payment:authorized',
  CAPTURED: 'payment:captured',
  PAID: 'payment:paid',
  FAILED: 'payment:failed',
  CANCELLED: 'payment:cancelled',
  EXPIRED: 'payment:expired',
  REFUNDED: 'payment:refunded',
  PARTIALLY_REFUNDED: 'payment:partially_refunded',
  DISPUTED: 'payment:disputed',
  CHARGEBACK: 'payment:chargeback',
  ARCHIVED: 'payment:archived',
  RESTORED: 'payment:restored',
  DELETED: 'payment:deleted',
  METHOD_CHANGED: 'payment:method_changed',
  AMOUNT_UPDATED: 'payment:amount_updated',
  AUTHORIZATION_EXTENDED: 'payment:authorization_extended',
})
