export const PAYMENT_STATUS = Object.freeze({
  DRAFT: 'draft',
  PENDING: 'pending',
  PROCESSING: 'processing',
  AUTHORIZED: 'authorized',
  PARTIALLY_PAID: 'partially_paid',
  PAID: 'paid',
  FAILED: 'failed',
  CANCELLED: 'cancelled',
  EXPIRED: 'expired',
  PARTIALLY_REFUNDED: 'partially_refunded',
  REFUNDED: 'refunded',
  DISPUTED: 'disputed',
  CHARGEBACK: 'chargeback',
  ARCHIVED: 'archived',
})

export const PAYMENT_STATUS_LIST = Object.values(PAYMENT_STATUS)

export const PAYMENT_STATUS_LABELS = Object.freeze({
  [PAYMENT_STATUS.DRAFT]: 'Draft',
  [PAYMENT_STATUS.PENDING]: 'Pending',
  [PAYMENT_STATUS.PROCESSING]: 'Processing',
  [PAYMENT_STATUS.AUTHORIZED]: 'Authorized',
  [PAYMENT_STATUS.PARTIALLY_PAID]: 'Partially Paid',
  [PAYMENT_STATUS.PAID]: 'Paid',
  [PAYMENT_STATUS.FAILED]: 'Failed',
  [PAYMENT_STATUS.CANCELLED]: 'Cancelled',
  [PAYMENT_STATUS.EXPIRED]: 'Expired',
  [PAYMENT_STATUS.PARTIALLY_REFUNDED]: 'Partially Refunded',
  [PAYMENT_STATUS.REFUNDED]: 'Refunded',
  [PAYMENT_STATUS.DISPUTED]: 'Disputed',
  [PAYMENT_STATUS.CHARGEBACK]: 'Chargeback',
  [PAYMENT_STATUS.ARCHIVED]: 'Archived',
})

export const PAYMENT_METHODS = Object.freeze({
  CREDIT_CARD: 'credit_card',
  DEBIT_CARD: 'debit_card',
  CASH: 'cash',
  BANK_TRANSFER: 'bank_transfer',
  WALLET: 'wallet',
  VOUCHER: 'voucher',
  MANUAL: 'manual',
  OTHER: 'other',
})

export const PAYMENT_METHOD_LIST = Object.values(PAYMENT_METHODS)

export function isTerminalStatus(status) {
  return [
    PAYMENT_STATUS.PAID,
    PAYMENT_STATUS.REFUNDED,
    PAYMENT_STATUS.CHARGEBACK,
    PAYMENT_STATUS.ARCHIVED,
  ].includes(status)
}

export function isActiveStatus(status) {
  return [
    PAYMENT_STATUS.DRAFT,
    PAYMENT_STATUS.PENDING,
    PAYMENT_STATUS.PROCESSING,
    PAYMENT_STATUS.AUTHORIZED,
    PAYMENT_STATUS.PARTIALLY_PAID,
    PAYMENT_STATUS.DISPUTED,
  ].includes(status)
}

export function isRefundableStatus(status) {
  return [
    PAYMENT_STATUS.PAID,
    PAYMENT_STATUS.PARTIALLY_PAID,
    PAYMENT_STATUS.AUTHORIZED,
  ].includes(status)
}

export function isCancellableStatus(status) {
  return [
    PAYMENT_STATUS.DRAFT,
    PAYMENT_STATUS.PENDING,
    PAYMENT_STATUS.PROCESSING,
    PAYMENT_STATUS.AUTHORIZED,
  ].includes(status)
}

export function isEditableStatus(status) {
  return [PAYMENT_STATUS.DRAFT].includes(status)
}

export function canTransitionTo(from, to) {
  const valid = VALID_TRANSITIONS[from]
  return valid ? valid.includes(to) : false
}

const VALID_TRANSITIONS = Object.freeze({
  [PAYMENT_STATUS.DRAFT]: [
    PAYMENT_STATUS.PENDING,
    PAYMENT_STATUS.CANCELLED,
    PAYMENT_STATUS.ARCHIVED,
  ],
  [PAYMENT_STATUS.PENDING]: [
    PAYMENT_STATUS.PROCESSING,
    PAYMENT_STATUS.CANCELLED,
    PAYMENT_STATUS.EXPIRED,
    PAYMENT_STATUS.ARCHIVED,
  ],
  [PAYMENT_STATUS.PROCESSING]: [
    PAYMENT_STATUS.AUTHORIZED,
    PAYMENT_STATUS.PAID,
    PAYMENT_STATUS.PARTIALLY_PAID,
    PAYMENT_STATUS.FAILED,
    PAYMENT_STATUS.CANCELLED,
  ],
  [PAYMENT_STATUS.AUTHORIZED]: [
    PAYMENT_STATUS.PAID,
    PAYMENT_STATUS.PARTIALLY_PAID,
    PAYMENT_STATUS.CANCELLED,
    PAYMENT_STATUS.REFUNDED,
    PAYMENT_STATUS.EXPIRED,
  ],
  [PAYMENT_STATUS.PARTIALLY_PAID]: [
    PAYMENT_STATUS.PAID,
    PAYMENT_STATUS.REFUNDED,
    PAYMENT_STATUS.PARTIALLY_REFUNDED,
    PAYMENT_STATUS.CHARGEBACK,
    PAYMENT_STATUS.DISPUTED,
  ],
  [PAYMENT_STATUS.PAID]: [
    PAYMENT_STATUS.REFUNDED,
    PAYMENT_STATUS.PARTIALLY_REFUNDED,
    PAYMENT_STATUS.CHARGEBACK,
    PAYMENT_STATUS.DISPUTED,
    PAYMENT_STATUS.ARCHIVED,
  ],
  [PAYMENT_STATUS.FAILED]: [
    PAYMENT_STATUS.PENDING,
    PAYMENT_STATUS.CANCELLED,
    PAYMENT_STATUS.ARCHIVED,
  ],
  [PAYMENT_STATUS.CANCELLED]: [
    PAYMENT_STATUS.ARCHIVED,
  ],
  [PAYMENT_STATUS.EXPIRED]: [
    PAYMENT_STATUS.PENDING,
    PAYMENT_STATUS.ARCHIVED,
  ],
  [PAYMENT_STATUS.PARTIALLY_REFUNDED]: [
    PAYMENT_STATUS.REFUNDED,
    PAYMENT_STATUS.PAID,
    PAYMENT_STATUS.CHARGEBACK,
    PAYMENT_STATUS.DISPUTED,
  ],
  [PAYMENT_STATUS.REFUNDED]: [
    PAYMENT_STATUS.ARCHIVED,
  ],
  [PAYMENT_STATUS.DISPUTED]: [
    PAYMENT_STATUS.PAID,
    PAYMENT_STATUS.REFUNDED,
    PAYMENT_STATUS.CHARGEBACK,
  ],
  [PAYMENT_STATUS.CHARGEBACK]: [
    PAYMENT_STATUS.ARCHIVED,
  ],
  [PAYMENT_STATUS.ARCHIVED]: [],
})
