export class BusinessSearch {
  static toPayload(business) {
    return {
      id: business.id,
      name: business.name,
      legal_name: business.legalName || null,
      slug: business.slug,
      description: business.description,
      status: business.status,
      type: 'business',
      category: business.category,
      subcategory: business.subcategory || null,
      destination_id: business.destinationId,
      tenant_id: business.tenantId,
      city: business.city || null,
      country: business.country || null,
      coordinates: business.coordinates || null,
      contact_email: business.contactEmail,
      contact_phone: business.contactPhone || null,
      website: business.website || null,
      logo: business.logo || null,
      cover_image: business.coverImage || null,
      verification_status: business.verificationStatus || null,
      visibility: business.visibility || 'public',
      language: business.language || null,
      currency: business.currency || null,
      timezone: business.timezone || null,
      published_accommodation_count: business.publishedAccommodationCount || 0,
      draft_accommodation_count: business.draftAccommodationCount || 0,
      rating: business.rating || null,
      accommodation_categories: business.accommodationCategories || [],
      availability_status: business.availabilityStatus || null,
      occupancy_rate: business.occupancyRate || null,
      total_bookable_days: business.totalBookableDays || 0,
      blocked_days: business.blockedDays || 0,
      reserved_days: business.reservedDays || 0,
      available_days: business.availableDays || 0,
      total_seasons: business.totalSeasons || 0,
      active_rules_count: business.activeRulesCount || 0,
      next_available_date: business.nextAvailableDate || null,
      last_availability_sync: business.lastAvailabilitySync || null,
      reservation_count: business.reservationCount || 0,
      active_reservations: business.activeReservations || 0,
      pending_reservations: business.pendingReservations || 0,
      confirmed_reservations: business.confirmedReservations || 0,
      checked_in: business.checkedInCount || 0,
      checked_out: 0,
      completed: business.completedCount || 0,
      cancelled: business.cancelledCount || 0,
      occupancy_rate: business.occupancyRate || null,
      average_stay: null,
      average_daily_rate: null,
      revpar: null,
      next_arrival: null,
      next_departure: null,
      today_arrivals: null,
      today_departures: null,
      future_revenue: business.totalRevenue || 0,
      last_reservation_sync: business.lastReservationSync || null,
      visitor_count: business.visitorCount || 0,
      active_visitors: business.activeVisitors || 0,
      vip_visitors: business.vipVisitors || 0,
      verified_visitors: business.verifiedVisitors || 0,
      blacklisted_visitors: business.blacklistedVisitors || 0,
      average_lifetime_value: business.averageLifetimeValue || null,
      average_stay: business.averageStay || null,
      repeat_rate: business.repeatRate || null,
      cancellation_rate: business.cancellationRate || null,
      no_show_rate: business.noShowRate || null,
      top_visitor: business.topVisitor || null,
      last_visitor: business.lastVisitor || null,
      visitor_tags: business.visitorTags || [],
      visitor_languages: business.visitorLanguages || [],
      visitor_countries: business.visitorCountries || [],
      visitor_segments: business.visitorSegments || [],
      last_visitor_sync: business.lastVisitorSync || null,
      payment_count: business.paymentCount || 0,
      payment_total: business.paymentTotal || 0,
      payment_pending: business.paymentPending || 0,
      payment_paid: business.paymentPaid || 0,
      payment_failed: business.paymentFailed || 0,
      payment_refunded: business.paymentRefunded || 0,
      payment_outstanding: business.paymentOutstanding || 0,
      payment_revenue: business.paymentRevenue || 0,
      payment_commission: business.paymentCommission || 0,
      payment_currency: business.currency || null,
      last_payment_sync: business.lastPaymentSync || null,
      notification_count: business.notificationCount || 0,
      pending_notifications: business.pendingNotifications || 0,
      failed_notifications: business.failedNotifications || 0,
      delivery_rate: business.deliveryRate || 0,
      notification_channel: null,
      last_notification: null,
      last_delivery: null,
      created_at: business.createdAt,
      updated_at: business.updatedAt,
      published_at: business.publishedAt,
    }
  }
}
