export const BUSINESS_EVENTS = {
  CREATED: 'business:created',
  UPDATED: 'business:updated',
  PUBLISHED: 'business:published',
  UNPUBLISHED: 'business:unpublished',
  ARCHIVED: 'business:archived',
  RESTORED: 'business:restored',
  DELETED: 'business:deleted',
  OWNER_CHANGED: 'business:owner_changed',
  VERIFIED: 'business:verified',
  ERROR: 'business:error',
}

export const BUSINESS_ACCOMMODATION_EVENTS = {
  ACCOMMODATION_CREATED: 'business.accommodation:created',
  ACCOMMODATION_ATTACHED: 'business.accommodation:attached',
  ACCOMMODATION_DETACHED: 'business.accommodation:detached',
  ACCOMMODATION_PUBLISHED: 'business.accommodation:published',
  ACCOMMODATION_HIDDEN: 'business.accommodation:hidden',
  ACCOMMODATION_ARCHIVED: 'business.accommodation:archived',
  ACCOMMODATION_DELETED: 'business.accommodation:deleted',
  ACCOMMODATION_TRANSFERRED: 'business.accommodation:transferred',
  ACCOMMODATION_ERROR: 'business.accommodation:error',
}

export const BUSINESS_AVAILABILITY_EVENTS = {
  CALENDAR_VIEWED: 'business.availability:calendar_viewed',
  OCCUPANCY_VIEWED: 'business.availability:occupancy_viewed',
  AVAILABILITY_VIEWED: 'business.availability:availability_viewed',
  DAY_BLOCKED: 'business.availability:day_blocked',
  DAY_UNBLOCKED: 'business.availability:day_unblocked',
  DAY_RESERVED: 'business.availability:day_reserved',
  DAY_RELEASED: 'business.availability:day_released',
  SEASON_APPLIED: 'business.availability:season_applied',
  SEASON_REMOVED: 'business.availability:season_removed',
  RULE_APPLIED: 'business.availability:rule_applied',
  RULE_REMOVED: 'business.availability:rule_removed',
  CALENDAR_COPIED: 'business.availability:calendar_copied',
  CALENDAR_DUPLICATED: 'business.availability:calendar_duplicated',
  BULK_UPDATED: 'business.availability:bulk_updated',
  STATISTICS_SYNCED: 'business.availability:statistics_synced',
  OCCUPANCY_RECALCULATED: 'business.availability:occupancy_recalculated',
  AVAILABILITY_REFRESHED: 'business.availability:availability_refreshed',
  ERROR: 'business.availability:error',
}

export const BUSINESS_RESERVATION_EVENTS = {
  RESERVATION_CREATED: 'business.reservation:created',
  RESERVATION_UPDATED: 'business.reservation:updated',
  RESERVATION_CONFIRMED: 'business.reservation:confirmed',
  RESERVATION_REJECTED: 'business.reservation:rejected',
  RESERVATION_CANCELLED: 'business.reservation:cancelled',
  RESERVATION_EXPIRED: 'business.reservation:expired',
  RESERVATION_CHECKED_IN: 'business.reservation:checked_in',
  RESERVATION_CHECKED_OUT: 'business.reservation:checked_out',
  RESERVATION_ARCHIVED: 'business.reservation:archived',
  RESERVATION_RESTORED: 'business.reservation:restored',
  RESERVATION_DELETED: 'business.reservation:deleted',
  RESERVATION_STATISTICS_UPDATED: 'business.reservation:statistics_updated',
  RESERVATION_DASHBOARD_UPDATED: 'business.reservation:dashboard_updated',
  RESERVATION_REVENUE_UPDATED: 'business.reservation:revenue_updated',
  RESERVATION_ERROR: 'business.reservation:error',
}

export const BUSINESS_VISITOR_EVENTS = {
  VISITOR_CREATED: 'business.visitor:created',
  VISITOR_UPDATED: 'business.visitor:updated',
  VISITOR_ARCHIVED: 'business.visitor:archived',
  VISITOR_RESTORED: 'business.visitor:restored',
  VISITOR_DELETED: 'business.visitor:deleted',
  VISITOR_MERGED: 'business.visitor:merged',
  VISITOR_ACTIVATED: 'business.visitor:activated',
  VISITOR_DEACTIVATED: 'business.visitor:deactivated',
  VISITOR_VERIFIED: 'business.visitor:verified',
  VISITOR_BLACKLISTED: 'business.visitor:blacklisted',
  VISITOR_UNBLACKLISTED: 'business.visitor:unblacklisted',
  VISITOR_VIP_GRANTED: 'business.visitor:vip_granted',
  VISITOR_VIP_REVOKED: 'business.visitor:vip_revoked',
  VISITOR_PROFILE_UPDATED: 'business.visitor:profile_updated',
  VISITOR_PREFERENCES_UPDATED: 'business.visitor:preferences_updated',
  VISITOR_TAGS_UPDATED: 'business.visitor:tags_updated',
  VISITOR_STATISTICS_UPDATED: 'business.visitor:statistics_updated',
  VISITOR_SEARCH_UPDATED: 'business.visitor:search_updated',
  RESERVATION_ATTACHED: 'business.visitor:reservation_attached',
  RESERVATION_DETACHED: 'business.visitor:reservation_detached',
  VISITOR_ERROR: 'business.visitor:error',
}

export const BUSINESS_PAYMENT_EVENTS = {
  PAYMENT_CREATED: 'business.payment:created',
  PAYMENT_UPDATED: 'business.payment:updated',
  PAYMENT_AUTHORIZED: 'business.payment:authorized',
  PAYMENT_CAPTURED: 'business.payment:captured',
  PAYMENT_PAID: 'business.payment:paid',
  PAYMENT_CANCELLED: 'business.payment:cancelled',
  PAYMENT_EXPIRED: 'business.payment:expired',
  PAYMENT_FAILED: 'business.payment:failed',
  PAYMENT_REFUNDED: 'business.payment:refunded',
  PAYMENT_PARTIALLY_REFUNDED: 'business.payment:partially_refunded',
  PAYMENT_ARCHIVED: 'business.payment:archived',
  PAYMENT_RESTORED: 'business.payment:restored',
  PAYMENT_DELETED: 'business.payment:deleted',
  PAYMENT_SUMMARY_UPDATED: 'business.payment:summary_updated',
  PAYMENT_SEARCH_UPDATED: 'business.payment:search_updated',
  PAYMENT_ERROR: 'business.payment:error',
}

export const BUSINESS_NOTIFICATION_EVENTS = {
  NOTIFICATION_CREATED: 'business.notification:created',
  NOTIFICATION_UPDATED: 'business.notification:updated',
  NOTIFICATION_SCHEDULED: 'business.notification:scheduled',
  NOTIFICATION_SENT: 'business.notification:sent',
  NOTIFICATION_DELIVERED: 'business.notification:delivered',
  NOTIFICATION_FAILED: 'business.notification:failed',
  NOTIFICATION_CANCELLED: 'business.notification:cancelled',
  NOTIFICATION_RETRIED: 'business.notification:retried',
  NOTIFICATION_ARCHIVED: 'business.notification:archived',
  NOTIFICATION_RESTORED: 'business.notification:restored',
  NOTIFICATION_DELETED: 'business.notification:deleted',
  NOTIFICATION_SUMMARY_UPDATED: 'business.notification:summary_updated',
  NOTIFICATION_SEARCH_UPDATED: 'business.notification:search_updated',
  NOTIFICATION_ERROR: 'business.notification:error',
}
