/**
 * Ecosystem Seed — Modules
 *
 * P12.3.1.5 — Initial Platform Seed Data
 *
 * Creates initial module configurations for ecosystems.
 * Modules represent platform capabilities that can be enabled per destination.
 */

export const MODULES_SEED = [
  // Core Modules
  {
    code: 'website',
    name: 'Website',
    slug: 'core-website',
    type: 'core',
    description: 'Basic website functionality with pages and navigation',
    version: '1.0.0',
    icon: 'bi-globe',
    capabilities: ['cms', 'public'],
    permissions: ['website:read', 'website:write'],
    isBuiltIn: true,
  },
  {
    code: 'experience',
    name: 'Experience Engine',
    slug: 'core-experience',
    type: 'core',
    description: 'Experience composition and rendering engine',
    version: '1.0.0',
    icon: 'bi-puzzle',
    capabilities: ['experience'],
    permissions: ['experience:read', 'experience:write'],
    isBuiltIn: true,
  },
  {
    code: 'profile',
    name: 'Company Profile',
    slug: 'core-profile',
    type: 'core',
    description: 'Business profile and company information management',
    version: '1.0.0',
    icon: 'bi-building',
    capabilities: ['business'],
    permissions: ['profile:read', 'profile:write'],
    isBuiltIn: true,
  },

  // Business Modules
  {
    code: 'reservations',
    name: 'Reservations',
    slug: 'business-reservations',
    type: 'business',
    description: 'Reservation booking and management system',
    version: '1.0.0',
    icon: 'bi-calendar-check',
    capabilities: ['reservation', 'booking'],
    permissions: ['reservation:read', 'reservation:write', 'reservation:manage'],
    isBuiltIn: false,
  },
  {
    code: 'availability',
    name: 'Availability',
    slug: 'business-availability',
    type: 'business',
    description: 'Availability calendar and management',
    version: '1.0.0',
    icon: 'bi-calendar',
    capabilities: ['availability'],
    permissions: ['availability:read', 'availability:write'],
    isBuiltIn: false,
  },
  {
    code: 'payments',
    name: 'Payments',
    slug: 'business-payments',
    type: 'business',
    description: 'Payment processing and invoicing',
    version: '1.0.0',
    icon: 'bi-credit-card',
    capabilities: ['payment', 'billing'],
    permissions: ['payment:read', 'payment:write', 'payment:process'],
    isBuiltIn: false,
  },
  {
    code: 'invoicing',
    name: 'Invoicing',
    slug: 'business-invoicing',
    type: 'business',
    description: 'Invoice generation and management',
    version: '1.0.0',
    icon: 'bi-receipt',
    capabilities: ['billing'],
    permissions: ['invoice:read', 'invoice:write', 'invoice:manage'],
    isBuiltIn: false,
  },
  {
    code: 'crm',
    name: 'CRM',
    slug: 'business-crm',
    type: 'business',
    description: 'Customer relationship management',
    version: '1.0.0',
    icon: 'bi-people',
    capabilities: ['visitor', 'engagement'],
    permissions: ['crm:read', 'crm:write', 'crm:manage'],
    isBuiltIn: false,
  },
  {
    code: 'notifications',
    name: 'Notifications',
    slug: 'business-notifications',
    type: 'business',
    description: 'Notification and messaging system',
    version: '1.0.0',
    icon: 'bi-bell',
    capabilities: ['notifications'],
    permissions: ['notification:read', 'notification:write', 'notification:send'],
    isBuiltIn: false,
  },

  // Content Modules
  {
    code: 'blog',
    name: 'Blog',
    slug: 'content-blog',
    type: 'content',
    description: 'Blog and article management',
    version: '1.0.0',
    icon: 'bi-journal-text',
    capabilities: ['cms'],
    permissions: ['blog:read', 'blog:write', 'blog:publish'],
    isBuiltIn: false,
  },
  {
    code: 'gallery',
    name: 'Gallery',
    slug: 'content-gallery',
    type: 'content',
    description: 'Image and media gallery management',
    version: '1.0.0',
    icon: 'bi-images',
    capabilities: ['cms'],
    permissions: ['gallery:read', 'gallery:write'],
    isBuiltIn: false,
  },
  {
    code: 'reviews',
    name: 'Reviews',
    slug: 'content-reviews',
    type: 'content',
    description: 'Review and rating system',
    version: '1.0.0',
    icon: 'bi-star',
    capabilities: ['community'],
    permissions: ['review:read', 'review:write', 'review:moderate'],
    isBuiltIn: false,
  },
  {
    code: 'events',
    name: 'Events',
    slug: 'content-events',
    type: 'content',
    description: 'Event management and calendar',
    version: '1.0.0',
    icon: 'bi-calendar-event',
    capabilities: ['cms', 'community'],
    permissions: ['event:read', 'event:write', 'event:manage'],
    isBuiltIn: false,
  },

  // Future Modules
  {
    code: 'marketplace',
    name: 'Marketplace',
    slug: 'future-marketplace',
    type: 'future',
    description: 'Multi-vendor marketplace functionality',
    version: '1.0.0',
    icon: 'bi-shop',
    capabilities: [],
    permissions: [],
    isBuiltIn: false,
  },
  {
    code: 'inventory',
    name: 'Inventory',
    slug: 'future-inventory',
    type: 'future',
    description: 'Inventory and stock management',
    version: '1.0.0',
    icon: 'bi-box-seam',
    capabilities: [],
    permissions: [],
    isBuiltIn: false,
  },
  {
    code: 'tickets',
    name: 'Tickets',
    slug: 'future-tickets',
    type: 'future',
    description: 'Ticketing and entry management',
    version: '1.0.0',
    icon: 'bi-ticket-perforated',
    capabilities: [],
    permissions: [],
    isBuiltIn: false,
  },
  {
    code: 'analytics',
    name: 'Analytics',
    slug: 'future-analytics',
    type: 'future',
    description: 'Business analytics and insights',
    version: '1.0.0',
    icon: 'bi-graph-up',
    capabilities: ['intelligence'],
    permissions: ['analytics:read', 'analytics:export'],
    isBuiltIn: false,
  },
]

export default MODULES_SEED
